services:

  db:
    image: postgres:17.0
    environment:
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "5432:5432"

  localstack:
    image: localstack/localstack
    container_name: localstack
    ports:
      - "4566:4566"
    environment:
      - SERVICES=s3, sns, sqs
      - DEFAULT_REGION=us-east-1